backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "src/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow

collections:
  - label: "panels"
    name: "panels"
    folder: "src/panels"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "images"
        name: "images"
        widget: "list"
        fields:
        - { label: "panel-images", name: "img", widget: "image", required: false }
        - { label: "panel-images-caption", name: "caption", widget: "string", required: false }
        required: false